# Generated by Django 2.2 on 2019-05-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realuser',
            name='name',
        ),
    ]
